# Generated by Django 4.2.2 on 2023-06-19 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resumes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='resume',
            managers=[
            ],
        ),
    ]
